version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    container_name: gittest
    hostname: 'git.rinlink.jp'
    ports:
      - "8085:8085"
      - "2225:22"
    entrypoint: |
      bash -c 'sed -i "s/MIN_CHARS_FOR_PARTIAL_MATCHING = 3/MIN_CHARS_FOR_PARTIAL_MATCHING = 1/g" /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sql/pattern.rb && /assets/wrapper'
    volumes:
      - '$PWD/config:/etc/gitlab'
      - '$PWD/logs:/var/log/gitlab'
      - '$PWD/data:/var/opt/gitlab'
      - '/etc/localtime:/etc/localtime:rw'
      - '$PWD/embedded-logs:/opt/gitlab/embedded/logs/'
    environment:
      DEBUG: 'false'
      GITLAB_PORT: 8085
      GITLAB_SSH_PORT: 22
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.rinlink.jp'
        nginx['client_max_body_size'] = '512m'
        nginx['listen_port'] = 8085
        nginx['enable'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['time_zone'] = 'Asia/Tokyo'



